### ISSUE TITLE
When is this going to be worked on again?

### ISSUE THREAD

**Issue by ollie-iterators** [iipc/qa2019#18]
I noticed that this project has not been worked on for a long time (It started in P.C. (Pre Covid)). I think that this project would be very important for archiving the internet. I think that the especially important areas are estimating completeness and grading quality of the archived version of a page.

I was wondering when this project is planned on being worked on again.

**Comment by anjackson** [comment]
Yeah, these were pretty much demos/prototypes thrown together during a hackathon. There is ongoing interest in many of these issues, and I agree completeness and grading would be very valuable.  However, there is very little development time available for these things at the moment, I'm afraid.
